# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a69cdd5de250fd71aac62c80301d17916db65db0617334491f029875acc87bbbb2c19bfb6061778b11e794e16d551261b2f38ecd6906cada74fd8464da28e3f5

test:
  secret_key_base: f6c20f8c17811874e8a4862173626fc3bc212a26ef44394f5cfa3be95cb222fa7c9c6e786b23cd4bc8f08ca21ceca040bae14f39f1f7aa501e33cd6bb108f67a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
